//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/+++Workdata/Scripts/Managers/UI/UiControllerMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UiControllerMap: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UiControllerMap()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UiControllerMap"",
    ""maps"": [
        {
            ""name"": ""UiActions"",
            ""id"": ""249eeb91-b797-4d02-9767-f610d9c2b70e"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""b00e8f4e-2f7e-4cf9-ae7c-c2e0316629d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ef2125f6-c057-4bf3-a749-fb710bb830b9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UiActions
        m_UiActions = asset.FindActionMap("UiActions", throwIfNotFound: true);
        m_UiActions_Pause = m_UiActions.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UiActions
    private readonly InputActionMap m_UiActions;
    private List<IUiActionsActions> m_UiActionsActionsCallbackInterfaces = new List<IUiActionsActions>();
    private readonly InputAction m_UiActions_Pause;
    public struct UiActionsActions
    {
        private @UiControllerMap m_Wrapper;
        public UiActionsActions(@UiControllerMap wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_UiActions_Pause;
        public InputActionMap Get() { return m_Wrapper.m_UiActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UiActionsActions set) { return set.Get(); }
        public void AddCallbacks(IUiActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_UiActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UiActionsActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IUiActionsActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IUiActionsActions instance)
        {
            if (m_Wrapper.m_UiActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUiActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_UiActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UiActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UiActionsActions @UiActions => new UiActionsActions(this);
    public interface IUiActionsActions
    {
        void OnPause(InputAction.CallbackContext context);
    }
}
